export const dynamic = "force-dynamic";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Nav = () => {
  return (
    <nav className="fixed bottom-0 flex h-8 w-full items-center justify-evenly bg-primary-content">
      <div>
        <Link href="/">Home</Link>
      </div>
      <div>
        <Link href="/build">Build</Link>
      </div>
      <div>
        <Link href="/routine">Routine</Link>
      </div>
      <div>
        <Link href="/discomfort">Fear</Link>
      </div>
      <div>
        <Link href="/goals">Goals</Link>
      </div>
    </nav>
  );
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html data-theme="dim" lang="en">
      <body className={`${inter.className} prose`}>
        <div className="navbar bg-neutral text-neutral-content">
          <button className="btn btn-ghost text-xl">Game of Life</button>
        </div>
        <div>{children}</div>
        <Nav />
      </body>
    </html>
  );
}
