export const dynamic = "force-dynamic";
import type { Metadata } from "next";
import { Inter, Space_Grotesk } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });
const spacegrotesk = Space_Grotesk({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Nav = () => {
  return (
    <nav className="fixed bottom-0 flex h-8 w-full items-center justify-evenly bg-primary-content">
      <div>
        <Link href="/">Home</Link>
      </div>
      <div>
        <Link href="/build">Build</Link>
      </div>
      <div>
        <Link href="/routine">Routine</Link>
      </div>
      <div>
        <Link href="/discomfort">Fear</Link>
      </div>
      <div>
        <Link href="/onething">One thing</Link>
      </div>
    </nav>
  );
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`${spacegrotesk.className} h-full`}>
        <div className="fixed h-16 px-8">
          <Link
            href="/"
            className="btn btn-ghost h-full p-0 text-xl text-black"
          >
            Game of Life
          </Link>
        </div>
        <div className="h-full">{children}</div>
        <Nav />
      </body>
    </html>
  );
}
